
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.l1_support
- system.openssh.server.team.l2_support
- cluster.mcp11_contrail_dpdk.openstack
- cluster.mcp11_contrail_dpdk.opencontrail
parameters:
  _param:
    apt_mk_version: nightly
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.1.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.1.qcow2

    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 172.16.52.117
    infra_config_deploy_address: 172.16.52.117
    
    cluster_domain: mcp11-contrail-dpdk.local
    cluster_name: mcp11_contrail_dpdk
    cluster_public_host: 172.16.55.230 #${_param:openstack_proxy_address}
    infra_kvm_address: 10.167.4.240
    infra_kvm_node01_address: 10.167.4.241
    infra_kvm_node02_address: 10.167.4.242
    infra_kvm_node03_address: 10.167.4.243
    infra_kvm_node01_deploy_address: 172.16.55.199
    infra_kvm_node02_deploy_address: 172.16.55.198
    infra_kvm_node03_deploy_address: 172.16.55.197
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0
    control_vlan: 1806
    tenant_vlan: 1807

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    deploy_network_netmask: 255.255.255.192
    deploy_network_gateway: 172.16.55.193

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}
    tenant_network_gateway: 10.167.6.1

  salt:
    minion:
      trusted_ca_minions:
        - cfg

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
